### DISCUSSION TITLE
tts to satelite?

### DISCUSSION THREAD

**Discussion by ignacio82** [FutureProofHomes/wyoming-enhancements#11] [Q&A] [answered]
Have you figure out how to do tts to your satelite from home assistant? I tried this:

```
service: tts.speak
target:
  entity_id: tts.piper
data:
  cache: true
  media_player_entity_id: media_player.pixel_7_pro_snapcast_client
  message: Can you hear this?
```

But it says that `snapcast_client does not support this service.`

**Comment by snootched** [comment]
On my satellites I added a dedicated TTS media_player entity based on the VLC telnet integration.
Hacky? Maybe.. Does it work?  Like a champ.

My voice alerts target the VLC entity (which has a pulseaudio role of notifications to invoke the ducking)
If you do go this way, you just have to clear the playlist after your tts message.


```
vlc-tts.service 

[Unit]
Description=VLC with Telnet port 4213 (HomeAssistant TTS)
After=network.target
After=pulseaudio.service
After=sound.target

[Service]

ExecStartPre=/bin/sleep 20
Environment="PULSE_SERVER=127.0.0.1"
ExecStart=/usr/bin/vlc --aout=pulse --role=notification -I telnet --telnet-port=4213 --telnet-password=<PASSWORD> --no-video --no-osd --no-one-instance -v
User=pi   
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Reply by ignacio82** [reply]
what packages do you need to install to get this to work? Could you share and example of the home assistant service that you use that sends the notifications and clears the playlist?  I tried the following

```
[Unit]
Description=VLC with Telnet port 4213 (HomeAssistant TTS)
After=network.target
After=pulseaudio.service
After=sound.target

[Service]

ExecStartPre=/bin/sleep 20
Environment="PULSE_SERVER=127.0.0.1"
ExecStart=/usr/bin/vlc --aout=pulse --role=notification -I telnet --telnet-port=4213 --telnet-password=a2EY53ri*g@8HUmftd --no-video --no-osd --no-one-instance -v
User=ignacio   
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

and I'm getting the following errors:

```
ignacio@mini-server:~$ journalctl -u vlc-tts.service  -f
Jan 23 04:42:50 mini-server systemd[1]: Starting VLC with Telnet port 4213 (HomeAssistant TTS)...
Jan 23 04:43:10 mini-server systemd[1]: Started VLC with Telnet port 4213 (HomeAssistant TTS).
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3a972220] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3aa1e4b0] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3aa1e4b0] main interface error: no suitable interface module
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3a8a1580] main libvlc error: interface "dbus,none" initialization failed
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3aa1dd30] main interface error: no suitable interface module
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3a8a1580] main libvlc error: interface "globalhotkeys,none" initialization failed
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3a940e40] main playlist: playlist is empty
Jan 23 04:43:10 mini-server vlc[35415]: [000055ae3aa1dd30] [telnet] lua interface: Listening on host "telnet://:4213".

```

```
$ groups ignacio
ignacio : ignacio adm cdrom sudo audio dip video plugdev render lxd pulse-access
```

Any ideas?

**Reply by ignacio82** [reply, marked as answer]
Removing `Environment="PULSE_SERVER=127.0.0.1"` solved my problem. No clue why.

**Reply by snootched** [reply]
Depends on how you've installed pulseaudio I believe.
Since mine is open on the network, and listening on tcp, I use 127.0.0.1 for local.
The normal PULSE* environment variables usually available on an interactive login are not available on the systemd unit - so I have to define it.

**Reply by snootched** [reply]
Missed replying to your other question about the playlist..
So VLC will by default just continue adding the TTS samples to its playlist - which then makes you think you're going crazy :)

To clear the playlist, you can use the following HA service call:

```
  - service: media_player.clear_playlist
    target:
      entity_id: "{{ my_speaker }}"             <-- put your VLC media_player entity here
    data: {}
```


If you are interested I can share my full TTS alert automation which leverages inputs for the satellite(s), criticality, notify android tv, etc. etc.  I use this across my system and it's built on top of [ChimeTTS](https://github.com/nimroddolev/chime_tts) which is a very cool project.  Right now, I just use the start chime, but the author has added quite a great bit of functionality recently.

**Reply by ignacio82** [reply]
Thanks. I would love to see the code for how you do it. This is what I'm doing right now:

```
alias: wyoming tts
sequence:
  - service: media_player.volume_set
    target:
      entity_id: "{{ player }}"
    data:
      volume_level: "{{ volume }}"
    enabled: true
  - service: tts.speak
    target:
      entity_id: tts.piper
    data:
      cache: true
      media_player_entity_id: "{{ player }}"
      message: "{{ message }}"
      options:
        voice: en-us-ignacio-train
  - wait_for_trigger:
      - platform: state
        entity_id:
          - media_player.family_room_wyoming
        to: idle
    timeout:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.clear_playlist
    data: {}
    target:
      entity_id: "{{ player }}"
fields:
  message:
    selector:
      text: null
    name: Message
    description: What do you want to say?
    required: true
  player:
    selector:
      entity:
        filter:
          integration: vlc_telnet
    name: Player
    required: true
    default: media_player.family_room_wyoming
  volume:
    selector:
      number:
        min: 0
        max: 1
        step: 0.1
        mode: slider
    required: true
    name: volume
    default: 0.5
mode: parallel
icon: mdi:microphone-message
max: 10
```

**Reply by snootched** [reply]
Sure - this is my script.  Could probably be more efficient, but works.  You could probably enhance it to target satellites that have occupancy etc - but my place is so small it doesn't matter.

I use a media_player group as my default notifications group (so I target multiple satellites with this - I don't try to send it through snapcast for sync'd TTS.  snapcast is only for music for me) 
`media_player.ha_notifications` contains two VLC media_player entities that have been added on the satellites and configured with VLC integration.  This actually works nicely withe the clear_playlist call, as it will clear each media_player in the group simultaneously.

In terms of the volume level - you could set the VLC volume stream in pulsemixer to a setting you like and just keep it there.  This is what I have done (set it in relation to other streams) then I just control the master PA volume.  Audio ducking kicks in when TTS is activated.

If you want to change it at runtime, then you can play with volume commands (also ChimeTTS supports volume manipulation.)
I submitted a PR to share how you can remotely set volumes etc, on the PA server if that's the way you want to go.

```
alias: tts_say_message_with_chime
fields:
  live_message:
    name: Live Message
    description: This will change the default message on-the-fly
    required: false
    example: This is where to put your message to be spoken
    selector:
      text:
        multiline: true
        type: text
  live_speaker:
    name: Live Media Player
    description: Change the default media player on the fly
    required: false
    selector:
      entity:
        multiple: true
        domain: media_player
    default:
      - media_player.ha_notifications
  criticality:
    name: Criticality
    description: This will affect the criticality of the message
    required: true
    default: normal
    example: normal | warning | critical
    selector:
      select:
        mode: dropdown
        options:
          - normal
          - warning
          - critical
        multiple: false
  custom_chime:
    selector:
      select:
        options:
          - normal
          - warning
          - critical
          - replicator
    name: Custom Chime
    description: Play a custom chime instead of the configured default for the criticality
variables:
  announcement_message: No message defined
  speaker_target: media_player.ha_notifications
  my_live_message: >-
    {% if live_message %} {{ live_message }} {% else %} {{ announcement_message
    }} {% endif %}
  my_speaker: >-
    {% if live_speaker %} {{ live_speaker }} {% else %} {{ speaker_target }} {%
    endif %}
  my_custom_chime: |-
    {% set chime = custom_chime if custom_chime else criticality %}
    {% if chime == 'normal' %}
      custom_chime_path_1
    {% elif chime == 'warning' %}
      custom_chime_path_2
    {% elif chime == 'critical' %}
      custom_chime_path_3
    {% elif chime == 'replicator' %}
      custom_chime_path_4
    {% elif chime == 'redalert' %}
      custom_chime_path_5
    {% endif %}
sequence:
  - service: chime_tts.say
    data:
      chime_path: "{{ my_custom_chime }}"
      delay: 750
      tts_playback_speed: 110
      message: "{{ my_live_message }}"
      tts_platform: cloud
      cache: true
      language: en-GB
      options: |-
        gender: female
        voice: SoniaNeural
    target:
      entity_id: "{{ my_speaker }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: media_player.clear_playlist
    target:
      entity_id: "{{ my_speaker }}"
    data: {}
mode: single
icon: mdi:script-text-play-outline
```

Example snippet from my main notification automation showing the call to TTS script:

```
...
...
parallel:
  - alias: TTS Notification
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.enable_verbal_notifications
            state: "on"
          - condition: template
            value_template: "{{ force_voice == true }}"
    then:
      - if:
          - condition: template
            value_template: "{{ chime == true }}"
        then:
          - service: script.tts_say_message_with_chime
            data:
              live_message: "{{ message }}"
              criticality: "{{ criticality }}"
              custom_chime: "{{ custom_chime }}"
            enabled: true
        else:
          - service: script.tts_say_message
            data:
              live_message: "{{ message }}"
            enabled: true
...
...
```
