### ISSUE TITLE
Getting error when trying to play music on satellite

### ISSUE THREAD

**Issue by milkplus27** [FutureProofHomes/wyoming-enhancements#24]
Hi there! Firstly, just wanted to say that you're doing awesome work here. Both video and written tutorials are easy to follow and a real asset to the HA community.

However, I seem to be having an issue which I'm certain is likely my own error but am a little stuck on how to debug it.

I have followed all your instructions to get to the point of having the Wyoming Satellite (with 2Mic PiHat) play music via either the wake word or just by typing into Assist in HA but i'm getting an errors back. If i ask it to play a specific artist on the specific device I get the following when i check the debug:

```
conversation_id: 01HP6C88NCJFXV8YWK3RSECC3R
device_id: null
intent_output:
  response:
    speech:
      plain:
        speech: >-
          Something went wrong: Error rendering data template: UndefinedError:
          list object has no element 0
        extra_data: null
    card: {}
    language: "*"
    response_type: error
    data:
      code: unknown
  conversation_id: 01HP6CF98SSTSXFQQYN1VFPE92
```

and then, if I ask it just to play a specific artist or genre (without specifying the device) i get this:

```
conversation_id: 01HP6CF98SSTSXFQQYN1VFPE92
device_id: null
intent_output:
  response:
    speech:
      plain:
        speech: "Something went wrong: Template rendered invalid entity IDs: "
        extra_data: null
    card: {}
    language: "*"
    response_type: error
    data:
      code: unknown
  conversation_id: 01HP6CFEJAGSM8G07Y0MXVK95K
```
At this point I'm not sure where I'm going wrong. What's interesting is that I had a different speaker (my Sonos soundbar) enabled in Music Assistant and had to disable it because when I said "Hey, Jarvis. Play Queen in the Living Room" it was playing on that speaker instead of the Wyoming Satellite. Which I didn't even think was possible.

Any advice would be super appreciated - I'm sure it's just me misunderstanding things haha
